version: '3.8'

services:
  celery_monitor:
    build: .
    ports:
      - "8099:8099"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://host.docker.internal:6379
      - CELERY_PERSISTENCE_URL=redis://redis:6379/1

    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:8.2.2
    ports:
      - "3000:3000"
    network_mode: "host"  # Use host network
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  redis-data:
  grafana-storage:
